//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_code { get; set; }
        public Nullable<int> entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string instruction { get; set; }
        public string question_header { get; set; }
        public Nullable<int> time { get; set; }
    }
}
