//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class jadwal
    {
        public int id { get; set; }
        public Nullable<int> id_paket_soal { get; set; }
        public string token { get; set; }
        public string mapel { get; set; }
        public Nullable<System.DateTime> waktu_mulai { get; set; }
        public Nullable<System.DateTime> waktu_selesei { get; set; }
        public string tempat { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string record_status { get; set; }
    }
}
