//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class jawaban
    {
        public int id { get; set; }
        public Nullable<int> id_jadwal { get; set; }
        public Nullable<int> id_soal { get; set; }
        public Nullable<int> id_siswa { get; set; }
        public Nullable<int> jawaban1 { get; set; }
        public Nullable<int> benar { get; set; }
        public string ragu { get; set; }
        public System.DateTime time { get; set; }
    }
}
