//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public int page_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string page_code { get; set; }
        public string page_name { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string icon { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
