//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilege
    {
        public int privilege_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> page_id { get; set; }
        public int entry_by { get; set; }
        public System.DateTime entry_date { get; set; }
    }
}
