//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class sekolah
    {
        public int id { get; set; }
        public string nama_sekolah { get; set; }
        public string tingkat { get; set; }
        public string IP { get; set; }
        public string alamat { get; set; }
        public Nullable<int> kota { get; set; }
        public Nullable<int> provinsi { get; set; }
        public string no_telp { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string nama_kepsek { get; set; }
        public string no_telp_kepsek { get; set; }
        public string email_kepsek { get; set; }
        public string nama_admin { get; set; }
        public string no_telp_admin { get; set; }
        public string email_admin { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tgl_aktivasi { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string record_status { get; set; }
    }
}
