//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNBK_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class soal
    {
        public int id { get; set; }
        public int id_mapel { get; set; }
        public string kode_soal { get; set; }
        public Nullable<int> jenis_soal { get; set; }
        public int kelas { get; set; }
        public string tingkat { get; set; }
        public int nomor_soal { get; set; }
        public string ragu { get; set; }
        public string tanya { get; set; }
        public string audio_tanya { get; set; }
        public string video_tanya { get; set; }
        public string gambar_tanya { get; set; }
        public string jawab1 { get; set; }
        public string jawab2 { get; set; }
        public string jawab3 { get; set; }
        public string jawab4 { get; set; }
        public string jawab5 { get; set; }
        public string gambar_jawab1 { get; set; }
        public string gambar_jawab2 { get; set; }
        public string gambar_jawab3 { get; set; }
        public string gambar_jawab4 { get; set; }
        public string gambar_jawab5 { get; set; }
        public string kunci_jawaban { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string record_status { get; set; }
    }
}
